id = "true-monokai-theme"
name = "True Monokai"
version = "0.0.1"
schema_version = 1
authors = ["Jig <nandajigyansu@gmail.com>"]
description = "The original Monokai theme for Zed, faithfully recreating the classic color palette and contrast of the OG Monokai."
repository = "https://github.com/jigyansunanda/true-monokai-for-zed"